### ISSUE TITLE
ValueError: not enough image data

### ISSUE THREAD

**Issue by Hazomo** [Nick2bad4u/BHBot-Exe#1]
not enough image data
Traceback (most recent call last):
  File "bot.py", line 328, in main_loop
  File "bot.py", line 301, in main_sequence
  File "bot.py", line 339, in get_states
  File "windows.py", line 172, in make_screenshot
  File "PIL\Image.py", line 3037, in frombuffer
  File "PIL\Image.py", line 2979, in frombytes
  File "PIL\Image.py", line 815, in frombytes
ValueError: not enough image data

happens occasionaly and needs restart, playing as nix

**Comment by Nick2bad4u** [comment]
> not enough image data Traceback (most recent call last): File "bot.py", line 328, in main_loop File "bot.py", line 301, in main_sequence File "bot.py", line 339, in get_states File "windows.py", line 172, in make_screenshot File "PIL\Image.py", line 3037, in frombuffer File "PIL\Image.py", line 2979, in frombytes File "PIL\Image.py", line 815, in frombytes ValueError: not enough image data
> 
> happens occasionaly and needs restart, playing as nix

Normally this happens when your game windows lags if I recall. Although no one else has reported it. Does this happen when your PC is under high load?

Edit: This is from resizing the brawlhalla window or minimizing it. I recommend using stealth mode (enable in settings) should fix it. If you do not want to run stealth, then make sure you don't minimize or resize the game window or it will crash.
